export const events = [
  {
    title: "Next.js Conf 2026",
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "Lisbon, Portugal",
    date: "March 10, 2026",
    time: "09:00 AM",
  },
  {
    title: "React Summit 2026",
    image: "/images/event2.png",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "April 22, 2026",
    time: "09:30 AM",
  },
  {
    title: "JSConf US 2026",
    image: "/images/event3.png",
    slug: "jsconf-us-2026",
    location: "Denver, CO, USA",
    date: "February 25, 2026",
    time: "10:00 AM",
  },
  {
    title: "PyCon US 2026",
    image: "/images/event4.png",
    slug: "pycon-us-2026",
    location: "Portland, OR, USA",
    date: "April 15, 2026",
    time: "08:30 AM",
  },
  {
    title: "HackMIT Winter 2026",
    image: "/images/event5.png",
    slug: "hackmit-winter-2026",
    location: "Cambridge, MA, USA",
    date: "January 17, 2026",
    time: "12:00 PM",
  },
  {
    title: "KubeCon + CloudNativeCon 2026",
    image: "/images/event6.png",
    slug: "kubecon-cloudnative-2026",
    location: "Barcelona, Spain",
    date: "May 12, 2026",
    time: "09:00 AM",
  },
];